// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjcF9M7EGJZ4H_HGf2VqpytHWH9ABCZb4',
    appId: '1:99197935716:web:eacf072e366fa84db6bf71',
    messagingSenderId: '99197935716',
    projectId: 'fairybeelullaby-bbc11',
    authDomain: 'fairybeelullaby-bbc11.firebaseapp.com',
    storageBucket: 'fairybeelullaby-bbc11.firebasestorage.app',
    measurementId: 'G-ENF6V5SRRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtw2XmzRY7B8qM_NX1GTN2y_dUsEHwCOw',
    appId: '1:99197935716:android:6bfc320d1171edceb6bf71',
    messagingSenderId: '99197935716',
    projectId: 'fairybeelullaby-bbc11',
    storageBucket: 'fairybeelullaby-bbc11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4B7Z0CjGUXLGKh7Z9vewSTwj-AJt-wZU',
    appId: '1:99197935716:ios:8efd84669999181fb6bf71',
    messagingSenderId: '99197935716',
    projectId: 'fairybeelullaby-bbc11',
    storageBucket: 'fairybeelullaby-bbc11.firebasestorage.app',
    iosBundleId: 'com.example.fairyBeeLullaby',
  );
}
